### ISSUE TITLE
put something like index.php under version1 or remove it

### ISSUE THREAD

**Issue by pinkdawn** [aws-samples/opsworks-demo-php-simple-app#1]
nice tutorial, but it's weird puts an empty version1 branch which has nothing.

I have to ssh to the ec2 instance to notice that nothing under /srv/www, and change app git branch to version2, it works.

**Comment by jeremeamia** [comment]
I'm not quite sure what you mean. Both the `version1` branch and the `version2` branches have an `index.php` file. The `version1` branch is used for [Step 1](http://docs.aws.amazon.com/opsworks/latest/userguide/gettingstarted.walkthrough.phpapp.1.html) of the walkthrough and the `version2` branch is used for [Step 2](http://docs.aws.amazon.com/opsworks/latest/userguide/gettingstarted.walkthrough.phpapp.2.html). Make sure to follow the walkthroughs closely because you'll need to set different values for **Document root** and **Branch/revision** in the AWS OpsWorks console for each step.
